Button Improvements
helpscout/hsds-react pull request #1003
Opened 2021-11-17 21:43 UTC by plbabin

This update improves the `Button` on numerous front:

## Button
### Functional component && forwardRef
First, we update the `Button` to be a functional component. The component was already really small, moving to functional allow us to implement `forwardRef` for the component. Because we had to support innerRef and buttonRef, but now those are all gone from the props list.

### RouteWrapper
This wrapper component was also problematic for forwardRef. It was messing up the ref prop passed down the Button. We did a quick investigation and we are not really sure what is the benefits of this old component. We decided to drop it while keeping the wrapper around just in case. If an issue occur with a `Button` or `Link`, we'll be able to fix it quickly by wrapping the component directly in hs-app.

### CSS variables & dropping `is-default`
The other big change on the `Button` component is the way CSS is handle. As we know it, there is **a lot** of kind, states and shape. It was hard to modify from the outside, and each state/kind was repeating some CSS when it was not needed. 

Now we leverage CSS variables to lay down the tokens foundation of the component. Each variable is assigned at the right place, and each kind, size & states will update only the variables.

Also, every time we wanted to use the Button component and update the style we had to increase the specificity of the selector by using `is-default`. We dropped styles from the `default` classname and moved them on the root component. That way any overwrites could be done by updating the CSS variables directly, making it easier than before to leverage `Button`

### Focus ring
`link` and `default` didn't had any focus ring. It didn't make sense since we want to have a visible focus state for every element on the page. Now both kind used the same pattern as the other button.

### New States
For the new reply bar, we needed to implement a couple of new state on the secondary button (`success`, `danger`). We also did update the "rounded" button to match the specs of those button:

![CleanShot 2021-11-17 at 16 18 05](https://user-images.githubusercontent.com/203992/142283927-bc4f4d44-557d-4ecb-8cd0-c5dcc76d1c0a.gif)
![CleanShot 2021-11-17 at 16 18 32](https://user-images.githubusercontent.com/203992/142283977-cb87304b-d53b-4cfd-9dba-f3de954695f4.gif)

### Props cleanup
While we were working on the component, we removed a lot of props that didn't make sense or were not used at all:

|  🪓 Props  |
|---|
| allowContentEventPropagation |
| disableOnLoading |
| fetch |
| buttonRef |
| spinButtonOnLoading |
| canRenderFocus |
| innerRef |
| isBlock |

## IconButton
Since the parent component changed a lot, we had to update the IconButton to overwrites CSS variables instead of css properties.

## Droplist Togglers IconBtn & MeatButton
Instead of creating a button from scratch, we update `MeatButton` and `IconBtn` to use `IconButton` behind the scene

## CopyButton
This component was refactord to be a functional one.  

## FocusRing
The focusRing mixin was update to leverage CSS variables, making it easier to reconfigure it based on the component using it.

```css
--focusRingOffset: -2px;
--focusRingShadow: ${focusShadow};
--focusRingRadius: inherit;
```

## Fixing things
Updating the component had some side effect on `Table`, `Pagination`, `DropList.SplittedButton`, `Condition`. Even though everything was minor, we fixed everything as part of this PR.

# Breaking change
When implementing this release on hs-app, we will have to validate & fix issues for a couple of things:
* Component overwriting through the `.is-default` classname
* Button `buttonRef` / `innerRef`

2021-11-19 11:44 UTC, tinkertrain approved these changes
I ❤️ this.

The use css variables is a win! I need to keep them in mind and use them more.

Also, thanks for updating related components like icon button, droplist togglers, etc 🙇

2021-11-22 04:36 UTC, digitaldesigner commented
This is cool, I'm all up for consistency and consolidation. Some discussion points below — basically the following would enable me to find consistency with this PR and the proposed new convo designs:

### Consolidation
- Seems like `kind=tertiary` is the same as `kind=secondary, state=success` — do we need tertiary at all?
- What is `state=grey` on the `kind=primary` button? Feels redundant, but if we keep I would encourage renaming to "muted" or perhaps change the name from "state" to "style" (since state in my mind refers to hover, focus etc)

### Min-Width and Padding
- Currently the secondary button doesn't have the same min-width as the primary, and I think it should (i.e. `min-width: 120px`
- However, `shape=rounded` shouldn't have any min-width
- The `SplittedButton` should also have no min-width on the text size of the component

### The Rounded Conundrum
- I need the `shape=rounded` to have have different properties to its square counterpart (see below). So I'm wondering whether it should be considered a `kind`, rather than a prop
  - Font-weight medium
  - Padding left/right: 20px
- Additionally, I need the rounded shape to be `44px` height. This is so it can match the `IconButton` in the fixed footer of the new convo design. However, 44px exists somewhere outside of the preset sizes. I'm reluctant to suggest another size

### Updates
- IconButton icon color should change from `charcoal.400` to `charcoal.500` on hover
- Would love for the IconButton to have a darker hover background (`grey.300` instead of `grey.200`) and an inset white border so that the background color and border don't clash (see image)

Not sure if this is helpful, but here's the breakdown of the ideal button types:
<img width="100%" src="https://user-images.githubusercontent.com/1317017/142801824-6d1a88e9-2c29-45fa-9608-ede8945ad63a.png">

2021-11-23 02:00 UTC, digitaldesigner commented
Trying to think out a more robust structure, wondering whether the "Primary", "Secondary" classifications are redundant? The following could apply to the regular button (i.e. continue to separate `Button` from `SplittedButton` and `IconButton`) and gives us 400+ style options:

| Style | Size | Is Rounded | State | Theme |
| :--- | :--- | :--- | :--- | :--- |
| Filled _(Default)_  | Large _(Default)_  | False _(Default)_  | None _(Default)_  | Blue  _(Default)_
| Outline  | Medium  | True  | Hover  | Mono
| Link | Small  |   | Active | Green
|  | X-Small  |   | Disabled | Red
|   | X-Large ⚠️  | | Loading
| | XX-Large ⚠️ 

⚠️ The existing `X-Large` (50px) today would become `XX-Large`, and the `X-Large` size can be used for the 44px chaos required by convo redesign

It's pretty chaotic, but allows us to support whatever is in the app currently but also the new convo stuff https://www.figma.com/file/Wp9mDxTvWicSTWtezj2ImkMP/HSDS-Product?node-id=10648%3A27724

2021-11-23 10:28 UTC, tinkertrain commented
@digitaldesigner 

> Trying to think out a more robust structure, wondering whether the "Primary", "Secondary" classifications are redundant? The following could apply to the regular button (i.e. continue to separate Button from SplittedButton and IconButton) and gives us 400+ style options

I'd love to have this if we get the chance, I really dislike how you can combine "kinds", "states" (success, warning),  and more into invalid or confusing states, for example I can set the button to state="warning" and kind="secondary" and I get a grey outlined button, (when warning is supposed to be yellow), same with kind="link" and any of the state colours. The "state" colours only seem to apply on "primary" or "tertiary" buttons. Even if we _never_ use red links, passing "link" and "red" should give you a red link, as that is what you would expect looking at the code.

The only problem is it will take some time to then apply the changes in HSApp and the rest... but I think is worth it.

2021-11-23 20:47 UTC, digitaldesigner commented
@tinkertrain Absolutely — I think that's just what happens as a result of bolting-on lots of properties over time. My proposed classifications still produce some versions of buttons we don't really use, but they're not terrible (and still accessible). For example in order to have a `rounded, outline` button for the new convo status, there are a couple of filled and non-rounded versions available of that same button we don't use elsewhere. That said, it gives us a lot more creative freedom and less chance of a designer needing to create a new variant since the available overrides are so expansive:

<img width="801" src="https://user-images.githubusercontent.com/1317017/143111612-aeef751e-0e05-4375-86b3-7731919e45cb.png">

2021-11-24 00:53 UTC, digitaldesigner commented
Was talking to @plbabin earlier about keeping `IconButton` as a separate component rather than provide it as a property within `Button`. The rationale is that by adding it to the Button scope, there's potential to create a whole load of outcomes that we don't ever want to support. Instead I think we should provide a similar set of configurations as `Button` but keep them limited to intended usage (i.e. no `theme:blue`, `isRounded:false`, `size:xs` or `state:loading` etc since we never have a need for those things).

So instead we'd have the following configs (where the sizes, themes and states correspond exactly to their Button counterpart):

| Style | Size | Has Text | State | Theme |
| :--- | :--- | :--- | :--- | :--- |
| Outline _(Default)_ | X-Large _(Default)_ | False _(Default)_ | None _(Default)_ | Gray _(Default)_ |
| Filled | Large | True | Hover | Green |
| | | | Active | Red |

Which result in [this many variants](https://www.figma.com/file/Wp9mDxTvWicSTWtezj2ImkMP/HSDS-Product?node-id=10658%3A27762) (72). As a proof of concept, the following designs are created entirely using the `Button` and `IconButton` components in varying states/props:

![New Convo Actions](https://user-images.githubusercontent.com/1317017/143151763-c5c34788-6158-4b0a-8af8-e5c1352f521d.png)

2021-12-01 21:48 UTC, plbabin commented
I think it's ready for another review, all internals buttons has been updated to the new props system

this is the script to update buttons: [scripts/codemod/transforms/ButtonStandardizationTransform.js](https://github.com/helpscout/hsds-react/blob/df005bd4b22fcf1c845095c2385a8931e99b4f1b/scripts/codemod/transforms/ButtonStandardizationTransform.js). That will help speeding thing up on hs-app-ui and hs-app

2021-12-02 04:42 UTC, digitaldesigner requested changes
Ooof, phenomenal amount of work — nice work @plbabin. Think I've gone through and tested just about every variant (I think), feedback below:

## Global
- This applies to every filled state — the border color should change to match the background so that it's one solid shape. So [in this case](https://c.hlp.sc/X6uby04N), the border should be `blue.600` (where it currently remains unchanged at `blue.500`) 

## Buttons/ Button
- `20px` instead of `30px` left and right padding on the `md,lg,xl,xxl` rounded buttons
- `theme:green, outlined:true, state:hover` border-color is too dark. There shouldn't be any change in the border color

## Icon Button
- `filled:false` should have an inner white border when there is no text (i.e. fill doesn't go to the edge on icon-only buttons). See [this image](https://c.hlp.sc/geupXolW)

## Question
- On all buttons, I'm wondering whether we could forego min-width and use only minimal padding when `linked:true` on Buttons/ Button? Feels unnecessary to force lots of whitespace. [This is the most common example I can think of](https://c.hlp.sc/2NuPZ02v)

2021-12-02 14:20 UTC, plbabin commented
@digitaldesigner all points have been taken care off, including the link `min-width`, I do think it look better that way! Let me know if you need anything else!

2021-12-02 16:39 UTC, jakubjanczyk commented
Hey @plbabin! I've heard about this update to the Button and I have one thing to consider.
I absolutely love the use of CSS variables here, however there must be an but :smile: 
The problem I see if for Beacon Embed. We don't use Button from HSDS directly there (as far as I understood it's because it was too heavy for our needs), but there is one instance of a Button that is used indirectly: `MessageCard.Button`.

Now there are two complications:
1. Since we are not using Button directly, we would need to update the styles in Beacon code to match the new styles, if they apply of course (I have not checked it yet, though)
2. CSS variables are not supported in IE11, that might make a problem for `MessageCard.Button`. To be honest, I have not read through the whole code, because there's a lot and I figured out it would be easier to ask at this point :) Are there any fallbacks that could be used in this case?
Also, Do I see correctly that usage of `theme` from `ThemeProvider` and `brandColor` has been removed from button? If so, the problem might be that we were using this feature to color MessageCard button with color selected for a beacon.

All of this might have been addressed already, but I have not seen anything in the discussion here or in the code. Sorry if it was! :)

2021-12-02 19:51 UTC, plbabin commented
> 
@jakubjanczyk 

That's some really great point. I went through the code in beacon and didn't found any Button instance without realizing that the brandColor code was for the MessageCard button. I went back and update the new button state to support brandColor https://github.com/helpscout/hsds-react/pull/1003/commits/488b5af1dbb46e4908c66d324275b7cd57017669

<img width="1028" alt="CleanShot 2021-12-02 at 14 24 21@2x" src="https://user-images.githubusercontent.com/203992/144489847-34a7afce-65ad-4aef-9ede-6c5ad52600e9.png">

It should be used only in a specific scenario like beacon

I added a couple of fallback values. It will not be a perfect solution, but the button should look like the grey one. Downside is that user on IE11 will not see the branded color, but at least they will see something. We would need to QA that! https://github.com/helpscout/hsds-react/pull/1003/commits/84c165383db60c0efca89408f935a6fdeb20a491

2021-12-03 04:00 UTC, digitaldesigner commented
Looking awesome, only one small change from me on the Button / IconButton where there's no text — the background fill should be a little darker on each of the themes. Borders and icon colors are fine, just the fills that need an update :)

![colors](https://user-images.githubusercontent.com/1317017/144541611-db44b4aa-aa5c-4053-8049-cdd813e72d5f.png)

Last thing, wondering if you'd be up for adding a couple darker pinks to the mix? Currently none of the pink range pass WCAG AA compliance, but it looks _so_ much better than red. If we added `#E9074B` as `pink.950` and `#C5003B` as `pink.1000` (both pass AA compliance) then we could swap out the entire red theme on all buttons for something a little... pinker. Thoughts?

![Pink](https://user-images.githubusercontent.com/1317017/144543103-d936f285-9a21-44d7-8a64-7bd9c111f90e.png)

2021-12-03 04:27 UTC, plbabin commented
Yes let's do it for pink. I can add it to colorway. Can you update the button with those colors in figma and I'll work on that tomorrow ! 

And the darker fill is really just for icon only button right?

2021-12-03 04:51 UTC, digitaldesigner commented
All done buddy — pink.950 and pink.1000 added and replaced all `theme:red` instances ([see Figma](https://www.figma.com/file/Wp9mDxTvWicSTWtezj2ImkMP/HSDS-Product?node-id=10648%3A27724)). Updated the previously attached image too, see below — and yes, the background fill only applies to the icon-only button

![Frame 17](https://user-images.githubusercontent.com/1317017/144547157-adb6f7d9-6b15-4dad-a164-7863f0e65905.png)

2021-12-03 08:44 UTC, jakubjanczyk commented
Thanks @plbabin! I've went ahead and updated hsds to the latest beta version in beacon repo and it all looks good in Chrome. I have no way to verify IE11 yet. I am only thinking if maybe the default value should be blue instead of grey, but that's something we can agree on :)

2021-12-03 16:51 UTC, plbabin commented
@jakubjanczyk I updated the default to be the `blue` theme. 

@digitaldesigner `theme=red` has been updated! Same with the icon only hover color

2021-12-06 04:13 UTC, digitaldesigner commented
This is looking great @plbabin — everything is addressed and looking great. However in testing I noticed that we use a version of the IconButton in `size:sm` and `theme:green` for the operator buttons in [`Forms/Condition`](https://hsds.helpscout.com/?path=/story/components-forms-condition--default-story). So in order to make that work, I'm going to need a couple spacing tweaks to the `size:sm` version of IconButton:

- No space between icon and text
- `10px` padding left
- `15px` padding right
- I know we discussed down-sizing the icon on Slack, but it feels like it should remain `24x24` in this instance.
- I'm also wondering whether we need a property for `isRounded` for this one too? Seeing as Condition uses these as square icons?

Here are the adjustments vs. the closest I could get using the existing component:
![Frame 17](https://user-images.githubusercontent.com/1317017/144786101-efca45fb-6fe8-4587-87c6-8d68178e1422.png)

2021-12-06 15:47 UTC, plbabin commented
@digitaldesigner I went in another direction. It felt like the proposed change to IconButton looked more like a regular button. So I added a prefix/suffix icon prop to allow adding an icon near the button content:

![CleanShot 2021-12-06 at 10 37 38](https://user-images.githubusercontent.com/203992/144876624-4311a1dd-7a44-46a2-b19d-25a8be010c9a.gif)

For the padding, since I wanted to support all sizes, I do a calculation with the current padding when there is an icon. I thought 8px looked better to have the same "padding" on both side, happy to change the value to whatever feels best to you 
https://github.com/helpscout/hsds-react/blob/424bbcaa1a4d575ac942d9689e9f9ed598319a32/src/components/Button/Button.css.js#L273-L280

This is how it looks within Condition (both `and` and `or` button used the new prop):

<img width="715" alt="CleanShot 2021-12-06 at 10 41 32@2x" src="https://user-images.githubusercontent.com/203992/144876939-5ad42c00-7f2b-4030-a06a-ab51951074cf.png">

2021-12-07 00:53 UTC, digitaldesigner commented
Yeah I love this. Everything is looking great from my side, and I've updated HSDS Figma to reflect the prefix/suffix icon

2021-12-07 03:12 UTC, digitaldesigner approved these changes
This is looking great. Million $ question though... how do we test this? Is there a way to get it onto Staging?

2021-12-07 04:58 UTC, plbabin commented
@digitaldesigner I'll tag you when it's ready on hs-app

2022-01-13 16:31 UTC, merged