Datepicker range
helpscout/hsds-react pull request #892
Opened 2020-11-18 14:36 UTC by tinkertrain

# Feature

In this PR we add the ability to select a range of dates in the Datepicker.

<img width="314" alt="Storybook 2020-11-18 15-31-45" src="https://user-images.githubusercontent.com/1414086/99543186-2e716400-29b3-11eb-8ed9-36e70a225569.png">

✅ Use the new `enableRangeSelection` prop (default false)
✅ Restrict the selection to a minimum number of days with `minBookingDays`
✅ After completing a selection range, starting a new one clears the existing one
✅ `onDateChange` returns both `startDate` and `endDate`
✅ Adds `type=button` to days to avoid triggering a form submit event in case you use the datepicker inside one.
✅ Adds a performance improvement with `useMemo`

2020-11-18 16:10 UTC, cen10 commented
@tinkertrain Not a blocker, but was curious if this would be a good PR to include the two changes we talked about when I was replacing the DatePicker in the Customers app - 
Inner ref: https://github.com/helpscout/hs-app/pull/9112/files#r515216437
Wrapper div: https://github.com/helpscout/hs-app/pull/9112#discussion_r512691125

2020-11-18 16:33 UTC, tinkertrain commented
> @tinkertrain Not a blocker, but was curious if this would be a good PR to include the two changes we talked about when I was replacing the DatePicker in the Customers app -
> Inner ref: [helpscout/hs-app#9112 (files)](https://github.com/helpscout/hs-app/pull/9112/files#r515216437)
> Wrapper div: [helpscout/hs-app#9112 (comment)](https://github.com/helpscout/hs-app/pull/9112#discussion_r512691125)

@cen10 Good call, thanks for reminding me 👍

2020-11-18 21:27 UTC, digitaldesigner requested changes
Amazing work! A couple of very minor UI updates required, but functionally working super well and exactly as expected (thanks for the video).

The bulk of my feedback is covered in **[ this loom video](https://www.loom.com/share/871fd4a5bd6747fc86fd8f8b66cc09d1)** — but also listed below:

- If "today" is within the selection, style it the same as other days (i.e. blue background)
- On hover of a 1st column range, the left side of the cell should be rounded (currently square)
- If the 1st column is the end range, there should be no light-blue square edge
- There's a weird bug where if you hover the bottom corner of a middle range (before end date is selected), the cell will oscillate between square and round (should remain rounded, see gif below)
- The grid for the day names is slightly different widths and x-pos offset to the date cells, which causes a visual mis-alignment for the day names. See below. Not a blocker, but once you see it, it cannot be unseen

### Weird mouse interaction
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1317017/99589403-0d0a8980-2a40-11eb-8fb4-66ec2f2f5378.gif)
### Cell alignment on days vs dates
![Frame 3](https://user-images.githubusercontent.com/1317017/99590060-f4e73a00-2a40-11eb-82d4-927b40c47a3a.png)

2020-11-18 21:29 UTC, digitaldesigner commented
On the above comment about the cell sizes, changing the day name cells to `36px` wide magically fixes everything. I might be over-simplifying things, but hopefully it's not a major structural change

![Screen Shot 2020-11-19 at 8 28 26 AM](https://user-images.githubusercontent.com/1317017/99590353-56a7a400-2a41-11eb-9932-1f95dda4948f.png)

2020-11-19 16:42 UTC, tinkertrain commented
@cen10 I have added the wrapper and the innerRef 👍 
@digitaldesigner Thanks for reviewing! I restructured some stuff and I think most if not all your points have been addressed... let me know!

2020-11-19 21:18 UTC, digitaldesigner commented
Thanks @tinkertrain — a few new bugs now:

- Hover states are missing for all cells, unless making a selection (should have a hover)
- On mouse down there's a focus border and the text moves a couple pixels (and shouldn't)
- If you select today as the start or end date the text is no longer visible
- Hovering over the left column mid-selection makes the right side of the cell flat and the left rounded (should be entirely rounded)

2020-11-20 11:07 UTC, tinkertrain commented
@digitaldesigner Thanks for taking the time to review!

1. Yikes I accidentally deleted those lines 🤦 
2...4 Fixed! 🤞

2020-11-23 00:13 UTC, digitaldesigner approved these changes
Looks awesome, thanks for your patience @tinkertrain

2020-11-26 20:43 UTC, plbabin approved these changes
thank you so much for taking care of that feature! The UX is spot on! nice work 🥇

2020-11-26 20:43 UTC, plbabin commented on src/components/Datepicker/Datepicker.js
> +  }, [datePickerRef])
I think that `datePickerRef.current` would trigger the useEffect callback correctly here (not 100% sure though, maybe just `datePickerRef` is fine)

2020-11-27 15:28 UTC, merged