Upgrade colorway to 0.9.6
helpscout/hsds-react pull request #985
Opened 2021-09-28 18:17 UTC by plbabin

This update adds two new color to the palette: `green.650` and `yellow.950`. We introduce those two blended shades to improves our accessibility effort across all application. They will be used to increase readability on a green or yellow background.

<img width="143" alt="CleanShot 2021-09-28 at 14 13 39@2x" src="https://user-images.githubusercontent.com/203992/135143211-9c06f46b-4001-43df-a69e-c28ae57447b2.png">
<img width="143" alt="CleanShot 2021-09-28 at 14 13 51@2x" src="https://user-images.githubusercontent.com/203992/135143224-d2496d3d-36c2-4c39-b81d-b3bf678cd85d.png">

2021-09-28 19:17 UTC, TerrenceLJones approved these changes
LGTM!

2021-09-29 00:51 UTC, digitaldesigner requested changes
Urh I hate to be *that* guy, but could we make that green `750` instead of `650`? On review its actually darker than `700`... so makes a bit more sense. Sorry. I'm sorry. Sorry.

2021-09-29 19:20 UTC, plbabin commented
> Urh I hate to be _that_ guy, but could we make that green `750` instead of `650`? On review its actually darker than `700`... so makes a bit more sense. Sorry. I'm sorry. Sorry.

you had to be _that_ guy 😉.

Everything has been updated from colorway to the PR description

2021-09-29 21:09 UTC, digitaldesigner approved these changes
You're a hero, thanks!

2021-09-30 14:33 UTC, merged